title: Project CPP 528
author: Jestrii Acosta, Kara Brick, Mariam Mahmoud , Megan Rowland , Rached Fares
description: Architect is a theme for GitHub Pages.
# Jekyll settings
permalinkm: /:title/
paginate: 2
exerpt_seproator: "n\n\n"
# Theme Setings
show_exerpts: false
date_format: "%B, %d, %Y"
dark_theme: true
dark_header: false
minimal_theme: true
naivgation:
  - 
  - index.md
  - about.md
  - test.md
 icons: #show icons in the header, for all possible icons see http://fontaesomw.io/icons/
 # envelope: "mailto:niklasbuschmann@users.noreply.github.com"
 #github: "https//github.com/R-Class.CPP-528-Project/edit/main"
 comments:
 #disqus: "disqus-contrast"
 #isso: "comments.mysite.org"
 remote_theme: niklasbuschmann/contrast
 pluginns:
 -jekyll-remote-theme
 -jekyll-feed
 -jekyll-paginate
 -jekyll-default-layout
 
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
